questions =  [
    {"id": 0, "question": "Communism is an unpractical system that will never work in practice.", "effects": {"cap": 1}},
    {"id": 1, "question": "Inheritance is a legitimate form of wealth.", "effects": {"cap": 1}},
    {"id": 2, "question": "Capitalism is the most successful and beneficial economic system yet.", "effects": {"cap": 1}},
    {"id": 3, "question": "The means of production should belong to the workers.", "effects": {"cap": -1}},
    {"id": 4, "question": "Basic utilities like roads and electricity should be publicly owned.", "effects": {"cap": -1}},
    {"id": 5, "question": "A community should suffer the gains and loss toghether.", "effects": {"cap": -1}},
    {"id": 6, "question": "A strong and large government is the best for society.", "effects": {"auth": 1}},
    {"id": 7, "question": "Even when protesting an authoritarian government, violence cannot be accepted.", "effects": {"auth": 1}},
    {"id": 8, "question": "Law and Order is more important than freedom and liberty.", "effects": {"auth": 1}},    
    {"id": 9, "question": "If a state exists, its size should be minimized.", "effects": {"auth": -1}},
    {"id": 10, "question": "The government should stay out of people's daily lives.", "effects": {"auth": -1}},
    {"id": 11, "question": "The existence of the state itself is a threat to our liberty.", "effects": {"auth": -1}},
    {"id": 12, "question": "Autocracy is better than Liberal Democracy.", "effects": {"auth": 1}},
    {"id": 12, "question": "It's important to prioritize our nation's interests over the rest of the world.", "effects": {"nat": 1}},
    {"id": 13, "question": "My nation is great.", "effects": {"nat": 1}},
    {"id": 14, "question": "Wars do not need to be justified towards other countries.", "effects": {"nat": 1}},
    {"id": 15, "question": "Nationalism is a selfish and evil ideology.", "effects": {"nat": -1}},
    {"id": 16, "question": "We should try to avoid wars and conflicts as much as possible.", "effects": {"nat": -1}},
    {"id": 17, "question": "A global country will be great for humanity.", "effects": {"nat": -1}},
    {"id": 18, "question": "Maintaining culture is very important.", "effects": {"trad": 1}},
    {"id": 19, "question": "We should maintain traditional values as much as possible.", "effects": {"trad": 1}},
    {"id": 20, "question": "We should not chase progress.", "effects": {"trad": 1}},
    {"id": 21, "question": "Society should be changed or reformed.", "effects": {"trad": -1}},
    {"id": 22, "question": "I support the LGBT community.", "effects": {"trad": -1}},
    {"id": 23, "question": "Progression is vital to human society.", "effects": {"trad": -1}},
    {"id": 24, "question": "The progression of technology has mostly been beneficial.", "effects": {"acc": 1}},
    {"id": 25, "question": "Developing advanced technology is the best way to solve climate change.", "effects": {"acc": 1}},
    {"id": 26, "question": "Life is harder and generally worse than it is a few decades ago.", "effects": {"acc": -1}},
    {"id": 27, "question": "Technological development should be slowed down.", "effects": {"acc": -1}},
    {"id": 28, "question": "Letting technology develop too much is very dangerous.", "effects": {"acc": -1}},
    {"id": 29, "question": "A God or a higher being exists.", "effects": {"relig": 1}},
    {"id": 30, "question": "My religion should be spread as much as possible.", "effects": {"relig": 1}},
    {"id": 31, "question": "I consider myself religious.", "effects": {"relig": 1}},
    {"id": 32, "question": "A religious government should be put in place.", "effects": {"relig": 1}},
    {"id": 33, "question": "Churches or other religious organization should be taxed as much as other organizations are.", "effects": {"relig": -1}},
    {"id": 34, "question": "My political ideas are fundementally different from the status quo.", "effects": {"rad": 1}},
    {"id": 35, "question": "A certain amount of violence is required in order to establish my ideology.", "effects": {"rad": 1}},
    {"id": 36, "question": "My ideology is 'mainstream'.", "effects": {"rad": -1}},
    {"id": 37, "question": "My political ideas can be established through small reforms.", "effects": {"rad": -1}},
    {"id": 38, "question": "Protests should be as peaceful as possible.", "effects": {"nonv": 1}},
    {"id": 39, "question": "Agression brings more negatives than positive.", "effects": {"nonv": 1}},
    {"id": 40, "question": "Violence is sometimes unavoidable in order to acheive real change.", "effects": {"nonv": -1}},
    {"id": 41, "question": "'Terrorist Attacks' are not as bad as what the general opinion thinks it is.", "effects": {"nonv": -1}},

];
