questions =  [
    {"id": 0, "question": "Communism is an unpractical system that will never work in practice.", "effects": {"cap": 1}},
    {"id": 1, "question": "Inheritance is a legitimate form of wealth.", "effects": {"cap": 1}},
    {"id": 2, "question": "Capitalism is the most successful and beneficial economic system yet.", "effects": {"cap": 1}},
    {"id": 3, "question": "The means of production should belong to the workers.", "effects": {"cap": -1}},
    {"id": 4, "question": "Basic utilities like roads and electricity should be publicly owned.", "effects": {"cap": -1}},
    {"id": 5, "question": "A community should suffer the gains and loss toghether.", "effects": {"cap": -1}},
    {"id": 6, "question": "A strong and large government is the best for society.", "effects": {"auth": 1}},
    {"id": 7, "question": "Even when protesting an authoritarian government, violence cannot be accepted.", "effects": {"auth": 1}},
    {"id": 8, "question": "Law and Order is more important than freedom and liberty.", "effects": {"auth": 1}},    
    {"id": 9, "question": "If a state exists, its size should be minimized.", "effects": {"auth": -1}},
    {"id": 10, "question": "The government should stay out of people's daily lives.", "effects": {"auth": -1}},
    {"id": 11, "question": "The existence of the state itself is a threat to our liberty.", "effects": {"auth": -1}},
    {"id": 12, "question": "It's important to prioritize our nation's interests over the rest of the world.", "effects": {"nat": 1}},
    {"id": 13, "question": "My nation is great.", "effects": {"nat": 1}},
    {"id": 14, "question": "Wars do not need to be justified towards other countries.", "effects": {"nat": 1}},
    {"id": 15, "question": "Nationalism is a selfish and evil ideology.", "effects": {"nat": -1}},
    {"id": 16, "question": "We should try to avoid wars and conflicts as much as possible.", "effects": {"nat": -1}},
    {"id": 17, "question": "A global country will be great for humanity.", "effects": {"nat": -1}},
    {"id": 18, "question": "Maintaining culture is very important.", "effects": {"trad": 1}},
    {"id": 19, "question": "We should maintain traditional values as much as possible.", "effects": {"trad": 1}},
    {"id": 20, "question": "We should not chase progress.", "effects": {"trad": 1}},
    {"id": 21, "question": "Society should be changed or reformed.", "effects": {"trad": -1}},
    {"id": 22, "question": "I support the LGBT community.", "effects": {"trad": -1}},
    {"id": 22, "question": "Progression is vital to human society.", "effects": {"trad": -1}},
    
];
